name: CI Pipeline
on:
  push:
    paths-ignore:
      - README.md
    branches:
      - '**'
    tags-ignore:
      - build-refs**
  pull_request:

jobs:
  lint:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9

  docker:
    needs: lint
    uses: chrisns/.github/.github/workflows/dockerbuild.yml@cebabbbee67cc9cc55c233518fcf9a7fa5f2d67d # main
    with:
      platforms: linux/arm64,linux/amd64,linux/arm/v7
