name: CI Pipeline
on:
  push:
    paths-ignore:
      - README.md
    branches:
      - '**'
    tags-ignore:
      - build-refs**
  pull_request:

jobs:
  lint:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: golangci/golangci-lint-action@ba0d7d2ec06a0ea1cb5fa41b2e4a3ab91d21278a # v9

  docker:
    needs: lint
    uses: chrisns/.github/.github/workflows/dockerbuild.yml@cebabbbee67cc9cc55c233518fcf9a7fa5f2d67d # main
    with:
      platforms: linux/arm64,linux/amd64,linux/arm/v7
